"""
Metacognitive Layer - Handles self-awareness, emotional intelligence, and persona adaptation
"""

import asyncio
import logging
from typing import Dict, Any, Optional, List, Tuple
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
import numpy as np
from collections import deque, Counter
import json
import re

logger = logging.getLogger(__name__)


class EmotionalState(Enum):
    """Detected emotional states of the user"""
    NEUTRAL = "neutral"
    FRUSTRATED = "frustrated"
    CONFUSED = "confused"
    ENGAGED = "engaged"
    BORED = "bored"
    ANXIOUS = "anxious"
    CONFIDENT = "confident"
    CURIOUS = "curious"
    TIRED = "tired"
    MOTIVATED = "motivated"


class PersonaTrait(Enum):
    """Persona traits that can be adjusted"""
    PATIENCE = "patience"
    ENTHUSIASM = "enthusiasm"
    FORMALITY = "formality"
    DETAIL_LEVEL = "detail_level"
    EMPATHY = "empathy"
    HUMOR = "humor"
    ENCOURAGEMENT = "encouragement"
    DIRECTNESS = "directness"


@dataclass
class PersonaConfig:
    """Configuration for AI persona"""
    patience_level: float = 0.8  # 0-1, higher = more patient
    enthusiasm_level: float = 0.7  # 0-1, higher = more enthusiastic
    formality_level: float = 0.5  # 0-1, higher = more formal
    detail_level: float = 0.6  # 0-1, higher = more detailed
    empathy_level: float = 0.7  # 0-1, higher = more empathetic
    humor_level: float = 0.3  # 0-1, higher = more humorous
    encouragement_level: float = 0.8  # 0-1, higher = more encouraging
    directness_level: float = 0.6  # 0-1, higher = more direct
    
    def to_dict(self) -> Dict[str, float]:
        return {
            'patience': self.patience_level,
            'enthusiasm': self.enthusiasm_level,
            'formality': self.formality_level,
            'detail': self.detail_level,
            'empathy': self.empathy_level,
            'humor': self.humor_level,
            'encouragement': self.encouragement_level,
            'directness': self.directness_level
        }


@dataclass
class UserState:
    """Current state of the user"""
    emotional_state: EmotionalState = EmotionalState.NEUTRAL
    confidence_level: float = 0.5  # 0-1
    engagement_level: float = 0.5  # 0-1
    fatigue_level: float = 0.3  # 0-1
    confusion_level: float = 0.2  # 0-1
    interest_topics: List[str] = field(default_factory=list)
    struggling_concepts: List[str] = field(default_factory=list)
    mastered_concepts: List[str] = field(default_factory=list)
    session_duration_minutes: float = 0.0
    interaction_count: int = 0
    last_active: datetime = field(default_factory=datetime.now)


@dataclass
class MetacognitiveInsight:
    """Insights generated by metacognitive layer"""
    detected_state: EmotionalState
    confidence: float
    suggested_persona_adjustments: Dict[PersonaTrait, float]
    reasoning: str
    intervention_needed: bool
    intervention_type: Optional[str] = None
    intervention_message: Optional[str] = None
    learning_patterns: Dict[str, Any] = field(default_factory=dict)


class MetacognitiveLayer:
    """
    Handles self-awareness, emotional intelligence, and persona adaptation.
    Monitors user state and adjusts AI behavior accordingly.
    """
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        
        # User states by session
        self.user_states: Dict[str, UserState] = {}
        
        # Persona configurations by session
        self.persona_configs: Dict[str, PersonaConfig] = {}
        
        # Default persona
        self.default_persona = PersonaConfig()
        
        # Emotional indicators (keywords and patterns)
        self.emotional_indicators = self._init_emotional_indicators()
        
        # Interaction history
        self.interaction_history: Dict[str, List[Dict[str, Any]]] = {}
        
        # Learning patterns by user
        self.learning_patterns: Dict[str, Dict[str, Any]] = {}
        
        # Emotion transition probabilities
        self.emotion_transitions = self._init_emotion_transitions()
        
        logger.info("Metacognitive Layer initialized")
    
    def _init_emotional_indicators(self) -> Dict[EmotionalState, Dict[str, Any]]:
        """Initialize emotional indicators for detection"""
        return {
            EmotionalState.FRUSTRATED: {
                'keywords': ['too hard', 'difficult', 'don\'t understand', 'confusing', 'frustrated', 'annoying'],
                'patterns': [r'why (is|are|does).+\?', r'this doesn\'t make sense', r'I don\'t get it'],
                'threshold': 0.6,
                'response_traits': {'patience': +0.2, 'encouragement': +0.3, 'directness': -0.1}
            },
            EmotionalState.CONFUSED: {
                'keywords': ['what', 'how', 'why', 'meaning', 'explain', 'clarify', 'unsure'],
                'patterns': [r'what (is|are|does)', r'how (do|does|can)', r'I\'m not sure'],
                'threshold': 0.5,
                'response_traits': {'patience': +0.2, 'detail': +0.2, 'enthusiasm': -0.1}
            },
            EmotionalState.ENGAGED: {
                'keywords': ['interesting', 'cool', 'awesome', 'understand', 'got it', 'makes sense'],
                'patterns': [r'that\'s (interesting|great|helpful)', r'I see', r'got it'],
                'threshold': 0.4,
                'response_traits': {'enthusiasm': +0.2, 'humor': +0.1, 'detail': +0.1}
            },
            EmotionalState.BORED: {
                'keywords': ['boring', 'tired', 'long', 'repetitive', 'again', 'already know'],
                'patterns': [r'this is boring', r'too long', r'heard this before'],
                'threshold': 0.5,
                'response_traits': {'enthusiasm': +0.3, 'detail': -0.2, 'humor': +0.2}
            },
            EmotionalState.ANXIOUS: {
                'keywords': ['nervous', 'worried', 'stress', 'exam', 'test', 'grade', 'fail'],
                'patterns': [r'I\'m (nervous|worried)', r'what if I fail', r'too much pressure'],
                'threshold': 0.5,
                'response_traits': {'empathy': +0.3, 'encouragement': +0.3, 'formality': +0.1}
            },
            EmotionalState.CONFIDENT: {
                'keywords': ['understand', 'know', 'easy', 'simple', 'clear', 'obvious'],
                'patterns': [r'I (understand|know|get it)', r'that\'s (easy|simple)', r'makes perfect sense'],
                'threshold': 0.4,
                'response_traits': {'detail': +0.2, 'challenge': +0.2, 'enthusiasm': +0.1}
            }
        }
    
    def _init_emotion_transitions(self) -> Dict[Tuple[EmotionalState, EmotionalState], float]:
        """Initialize probability matrix for emotion transitions"""
        transitions = {}
        
        # Neutral transitions
        transitions[(EmotionalState.NEUTRAL, EmotionalState.ENGAGED)] = 0.3
        transitions[(EmotionalState.NEUTRAL, EmotionalState.CONFUSED)] = 0.2
        transitions[(EmotionalState.NEUTRAL, EmotionalState.BORED)] = 0.1
        
        # Frustrated transitions
        transitions[(EmotionalState.FRUSTRATED, EmotionalState.ANXIOUS)] = 0.4
        transitions[(EmotionalState.FRUSTRATED, EmotionalState.CONFUSED)] = 0.3
        transitions[(EmotionalState.FRUSTRATED, EmotionalState.ENGAGED)] = 0.2
        
        # Confused transitions
        transitions[(EmotionalState.CONFUSED, EmotionalState.FRUSTRATED)] = 0.3
        transitions[(EmotionalState.CONFUSED, EmotionalState.ENGAGED)] = 0.4
        transitions[(EmotionalState.CONFUSED, EmotionalState.CURIOUS)] = 0.2
        
        # Engaged transitions
        transitions[(EmotionalState.ENGAGED, EmotionalState.CONFIDENT)] = 0.3
        transitions[(EmotionalState.ENGAGED, EmotionalState.CURIOUS)] = 0.3
        transitions[(EmotionalState.ENGAGED, EmotionalState.NEUTRAL)] = 0.2
        
        return transitions
    
    async def process(self,
                     user_input: str,
                     session_id: str,
                     context: Optional[Dict[str, Any]] = None) -> MetacognitiveInsight:
        """
        Process user input to generate metacognitive insights
        
        Args:
            user_input: User's message
            session_id: Current session identifier
            context: Additional context information
            
        Returns:
            MetacognitiveInsight with emotional detection and persona adjustments
        """
        context = context or {}
        
        try:
            # Get or create user state
            user_state = self._get_user_state(session_id)
            
            # Update session metrics
            user_state.interaction_count += 1
            user_state.last_active = datetime.now()
            
            # Detect emotional state
            detected_state, confidence = await self._detect_emotional_state(user_input, user_state)
            
            # Update user state with detected emotion
            previous_state = user_state.emotional_state
            user_state.emotional_state = detected_state
            
            # Check for emotion transition patterns
            transition_key = (previous_state, detected_state)
            transition_probability = self.emotion_transitions.get(transition_key, 0.1)
            
            # Analyze learning patterns
            learning_patterns = self._analyze_learning_patterns(user_input, session_id)
            
            # Generate persona adjustments
            adjustments = self._calculate_persona_adjustments(
                detected_state, 
                confidence, 
                user_state,
                learning_patterns
            )
            
            # Determine if intervention is needed
            intervention_needed, intervention_type, intervention_message = \
                self._check_intervention_needed(user_state, detected_state, learning_patterns)
            
            # Generate reasoning
            reasoning = self._generate_insight_reasoning(
                previous_state, 
                detected_state, 
                confidence, 
                user_state,
                learning_patterns
            )
            
            # Update persona configuration
            self._update_persona_config(session_id, adjustments)
            
            # Store interaction in history
            self._store_interaction(session_id, {
                'timestamp': datetime.now(),
                'input': user_input,
                'detected_state': detected_state.value,
                'confidence': confidence,
                'adjustments': {k.value: v for k, v in adjustments.items()}
            })
            
            return MetacognitiveInsight(
                detected_state=detected_state,
                confidence=confidence,
                suggested_persona_adjustments=adjustments,
                reasoning=reasoning,
                intervention_needed=intervention_needed,
                intervention_type=intervention_type,
                intervention_message=intervention_message,
                learning_patterns=learning_patterns
            )
            
        except Exception as e:
            logger.error(f"Error in metacognitive processing: {str(e)}", exc_info=True)
            return MetacognitiveInsight(
                detected_state=EmotionalState.NEUTRAL,
                confidence=0.5,
                suggested_persona_adjustments={},
                reasoning=f"Error in detection: {str(e)}",
                intervention_needed=False,
                learning_patterns={}
            )
    
    def _get_user_state(self, session_id: str) -> UserState:
        """Get or create user state for session"""
        if session_id not in self.user_states:
            self.user_states[session_id] = UserState()
            
            # Initialize persona config
            self.persona_configs[session_id] = PersonaConfig()
            
            # Initialize interaction history
            self.interaction_history[session_id] = []
            
            # Initialize learning patterns
            self.learning_patterns[session_id] = {
                'preferred_topics': [],
                'struggle_topics': [],
                'mastered_topics': [],
                'average_response_time': 0,
                'help_requests': 0,
                'session_count': 0
            }
        
        return self.user_states[session_id]
    
    async def _detect_emotional_state(self, 
                                     user_input: str, 
                                     user_state: UserState) -> Tuple[EmotionalState, float]:
        """
        Detect emotional state from user input using multiple signals
        """
        input_lower = user_input.lower()
        
        # Calculate scores for each emotion
        emotion_scores = {}
        
        for emotion, indicators in self.emotional_indicators.items():
            score = 0.0
            matches = 0
            
            # Check keywords
            for keyword in indicators['keywords']:
                if keyword in input_lower:
                    score += 0.3
                    matches += 1
            
            # Check patterns
            for pattern in indicators['patterns']:
                if re.search(pattern, input_lower, re.IGNORECASE):
                    score += 0.4
                    matches += 1
            
            # Consider punctuation and text features
            if '?' in user_input and emotion in [EmotionalState.CONFUSED, EmotionalState.CURIOUS]:
                score += 0.2
            elif '!' in user_input and emotion in [EmotionalState.FRUSTRATED, EmotionalState.ENGAGED]:
                score += 0.2
            
            # Consider word count (very short responses might indicate frustration/boredom)
            word_count = len(user_input.split())
            if word_count < 3 and emotion in [EmotionalState.FRUSTRATED, EmotionalState.BORED]:
                score += 0.1
            elif word_count > 20 and emotion in [EmotionalState.ENGAGED, EmotionalState.CURIOUS]:
                score += 0.1
            
            # Normalize score based on matches
            if matches > 0:
                score = min(score, 1.0)
                emotion_scores[emotion] = score
        
        # Consider session context
        self._apply_contextual_emotion(emotion_scores, user_state)
        
        # Get highest scoring emotion
        if emotion_scores:
            detected_emotion = max(emotion_scores.items(), key=lambda x: x[1])
            confidence = detected_emotion[1]
            
            # Apply confidence threshold
            threshold = self.emotional_indicators.get(detected_emotion[0], {}).get('threshold', 0.3)
            if confidence < threshold:
                return EmotionalState.NEUTRAL, 0.5
                
            return detected_emotion[0], confidence
        
        return EmotionalState.NEUTRAL, 0.5
    
    def _apply_contextual_emotion(self, emotion_scores: Dict[EmotionalState, float], user_state: UserState):
        """Apply contextual factors to emotion detection"""
        
        # Fatigue factor - longer sessions may indicate fatigue
        if user_state.session_duration_minutes > 30:
            if EmotionalState.TIRED in emotion_scores:
                emotion_scores[EmotionalState.TIRED] += 0.2
            else:
                emotion_scores[EmotionalState.TIRED] = 0.2
        
        # Engagement factor - many interactions might indicate engagement
        if user_state.interaction_count > 20:
            if EmotionalState.ENGAGED in emotion_scores:
                emotion_scores[EmotionalState.ENGAGED] += 0.2
            else:
                emotion_scores[EmotionalState.ENGAGED] = 0.2
        
        # Previous emotion influence - emotions tend to persist
        previous_emotion = user_state.emotional_state
        if previous_emotion in emotion_scores:
            emotion_scores[previous_emotion] += 0.1
    
    def _calculate_persona_adjustments(self,
                                      detected_state: EmotionalState,
                                      confidence: float,
                                      user_state: UserState,
                                      learning_patterns: Dict[str, Any]) -> Dict[PersonaTrait, float]:
        """Calculate persona adjustments based on detected state"""
        adjustments = {}
        
        # Get adjustment template for detected emotion
        emotion_config = self.emotional_indicators.get(detected_state, {})
        trait_adjustments = emotion_config.get('response_traits', {})
        
        for trait_name, adjustment in trait_adjustments.items():
            try:
                trait = PersonaTrait[trait_name.upper()]
                # Scale adjustment by confidence
                adjustments[trait] = adjustment * confidence
            except KeyError:
                continue
        
        # Consider learning patterns
        if learning_patterns.get('struggle_topics'):
            # More patience and encouragement if struggling
            adjustments[PersonaTrait.PATIENCE] = adjustments.get(PersonaTrait.PATIENCE, 0) + 0.1
            adjustments[PersonaTrait.ENCOURAGEMENT] = adjustments.get(PersonaTrait.ENCOURAGEMENT, 0) + 0.1
        
        if learning_patterns.get('mastered_topics'):
            # More challenge if mastering topics
            adjustments[PersonaTrait.DETAIL_LEVEL] = adjustments.get(PersonaTrait.DETAIL_LEVEL, 0) + 0.1
        
        # Consider fatigue
        if user_state.fatigue_level > 0.7:
            # Be more concise and encouraging if user is tired
            adjustments[PersonaTrait.DETAIL_LEVEL] = adjustments.get(PersonaTrait.DETAIL_LEVEL, 0) - 0.2
            adjustments[PersonaTrait.ENTHUSIASM] = adjustments.get(PersonaTrait.ENTHUSIASM, 0) + 0.2
        
        # Clip adjustments to reasonable range
        for trait in adjustments:
            adjustments[trait] = max(-0.5, min(0.5, adjustments[trait]))
        
        return adjustments
    
    def _check_intervention_needed(self,
                                  user_state: UserState,
                                  detected_state: EmotionalState,
                                  learning_patterns: Dict[str, Any]) -> Tuple[bool, Optional[str], Optional[str]]:
        """Check if an intervention is needed"""
        
        # Check for high frustration
        if detected_state == EmotionalState.FRUSTRATED and user_state.confusion_level > 0.6:
            return True, "frustration_intervention", "I notice you seem frustrated. Would you like to try a different approach or take a short break?"
        
        # Check for prolonged confusion
        if detected_state == EmotionalState.CONFUSED and user_state.confusion_level > 0.5:
            if user_state.interaction_count > 5:
                return True, "confusion_intervention", "It seems like you're having difficulty with this concept. Would you like me to explain it differently or provide some examples?"
        
        # Check for boredom
        if detected_state == EmotionalState.BORED and user_state.engagement_level < 0.3:
            return True, "engagement_intervention", "Would you like to explore a different topic or try some interactive exercises?"
        
        # Check for anxiety before tests
        if detected_state == EmotionalState.ANXIOUS:
            return True, "anxiety_intervention", "Remember to take deep breaths. You've got this! Would you like some test-taking strategies or a quick review?"
        
        # Check for low confidence
        if user_state.confidence_level < 0.3:
            return True, "confidence_intervention", "You're making progress! Remember that learning takes time. Would you like to review some topics you've already mastered?"
        
        return False, None, None
    
    def _analyze_learning_patterns(self, user_input: str, session_id: str) -> Dict[str, Any]:
        """Analyze learning patterns from user input"""
        patterns = self.learning_patterns.get(session_id, {})
        
        # Detect topic mentions
        topics = self._extract_topics(user_input)
        
        # Update preferred topics (topics mentioned frequently)
        for topic in topics:
            if topic not in patterns.get('preferred_topics', []):
                if 'preferred_topics' not in patterns:
                    patterns['preferred_topics'] = []
                patterns['preferred_topics'].append(topic)
        
        # Detect struggle indicators
        struggle_indicators = ['don\'t understand', 'confusing', 'too hard', 'difficult']
        if any(indicator in user_input.lower() for indicator in struggle_indicators):
            for topic in topics:
                if topic not in patterns.get('struggle_topics', []):
                    if 'struggle_topics' not in patterns:
                        patterns['struggle_topics'] = []
                    patterns['struggle_topics'].append(topic)
        
        # Detect mastery indicators
        mastery_indicators = ['understand', 'got it', 'makes sense', 'easy']
        if any(indicator in user_input.lower() for indicator in mastery_indicators):
            for topic in topics:
                if topic not in patterns.get('mastered_topics', []):
                    if 'mastered_topics' not in patterns:
                        patterns['mastered_topics'] = []
                    patterns['mastered_topics'].append(topic)
        
        # Update patterns
        self.learning_patterns[session_id] = patterns
        
        return patterns
    
    def _extract_topics(self, text: str) -> List[str]:
        """Extract potential topic keywords from text"""
        # Simple noun phrase extraction
        # In production, use NLP library like spaCy
        words = text.split()
        topics = []
        
        # Look for capitalized words (potential proper nouns)
        for word in words:
            if word[0].isupper() and len(word) > 2:
                topics.append(word.lower())
        
        # Look for technical terms (simplified)
        technical_indicators = ['calculus', 'physics', 'chemistry', 'algorithm', 'function']
        for indicator in technical_indicators:
            if indicator in text.lower():
                topics.append(indicator)
        
        return topics[:5]  # Limit to 5 topics
    
    def _generate_insight_reasoning(self,
                                   previous_state: EmotionalState,
                                   current_state: EmotionalState,
                                   confidence: float,
                                   user_state: UserState,
                                   learning_patterns: Dict[str, Any]) -> str:
        """Generate human-readable reasoning for insights"""
        reasons = []
        
        # State transition
        if previous_state != current_state:
            reasons.append(f"Emotional state shifted from {previous_state.value} to {current_state.value}")
        else:
            reasons.append(f"Consistent {current_state.value} state detected")
        
        # Confidence level
        if confidence > 0.8:
            reasons.append("High confidence in detection")
        elif confidence < 0.5:
            reasons.append("Low confidence - considering neutral baseline")
        
        # Session context
        if user_state.session_duration_minutes > 30:
            reasons.append(f"Long session ({user_state.session_duration_minutes:.0f} minutes)")
        
        if user_state.fatigue_level > 0.7:
            reasons.append("High fatigue levels detected")
        
        # Learning patterns
        if learning_patterns.get('struggle_topics'):
            topics = learning_patterns['struggle_topics'][-3:]
            reasons.append(f"Struggling with: {', '.join(topics)}")
        
        if learning_patterns.get('mastered_topics'):
            topics = learning_patterns['mastered_topics'][-3:]
            reasons.append(f"Mastered: {', '.join(topics)}")
        
        return " | ".join(reasons)
    
    def _update_persona_config(self, session_id: str, adjustments: Dict[PersonaTrait, float]):
        """Update persona configuration with adjustments"""
        if session_id not in self.persona_configs:
            self.persona_configs[session_id] = PersonaConfig()
        
        config = self.persona_configs[session_id]
        
        for trait, adjustment in adjustments.items():
            current_value = getattr(config, f"{trait.value}_level", 0.5)
            new_value = current_value + adjustment
            
            # Clamp to [0, 1]
            new_value = max(0.0, min(1.0, new_value))
            
            # Update config
            setattr(config, f"{trait.value}_level", new_value)
    
    def _store_interaction(self, session_id: str, interaction: Dict[str, Any]):
        """Store interaction in history"""
        if session_id in self.interaction_history:
            self.interaction_history[session_id].append(interaction)
            
            # Keep only last 100 interactions
            if len(self.interaction_history[session_id]) > 100:
                self.interaction_history[session_id] = self.interaction_history[session_id][-100:]
    
    def get_persona_config(self, session_id: str) -> PersonaConfig:
        """Get current persona configuration for session"""
        return self.persona_configs.get(session_id, self.default_persona)
    
    def update_session_duration(self, session_id: str, duration_minutes: float):
        """Update session duration for user"""
        if session_id in self.user_states:
            self.user_states[session_id].session_duration_minutes = duration_minutes
    
    def get_user_state_summary(self, session_id: str) -> Dict[str, Any]:
        """Get summary of user state"""
        if session_id not in self.user_states:
            return {}
        
        state = self.user_states[session_id]
        patterns = self.learning_patterns.get(session_id, {})
        
        return {
            'emotional_state': state.emotional_state.value,
            'confidence_level': state.confidence_level,
            'engagement_level': state.engagement_level,
            'fatigue_level': state.fatigue_level,
            'confusion_level': state.confusion_level,
            'session_duration': state.session_duration_minutes,
            'interaction_count': state.interaction_count,
            'preferred_topics': patterns.get('preferred_topics', []),
            'struggle_topics': patterns.get('struggle_topics', []),
            'mastered_topics': patterns.get('mastered_topics', [])
        }
    
    def get_session_statistics(self, session_id: str) -> Dict[str, Any]:
        """Get statistics for a session"""
        if session_id not in self.interaction_history:
            return {}
        
        history = self.interaction_history[session_id]
        
        if not history:
            return {}
        
        # Count emotion occurrences
        emotion_counts = Counter()
        for interaction in history:
            emotion_counts[interaction['detected_state']] += 1
        
        # Calculate average confidence
        avg_confidence = np.mean([i['confidence'] for i in history])
        
        return {
            'total_interactions': len(history),
            'emotion_distribution': dict(emotion_counts),
            'average_confidence': avg_confidence,
            'first_interaction': history[0]['timestamp'],
            'last_interaction': history[-1]['timestamp']
        }