"""
Proactive Layer - Analyzes learning patterns and generates proactive interventions
"""

import asyncio
import logging
from typing import Dict, Any, Optional, List, Tuple, Callable
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
import numpy as np
from collections import deque, defaultdict
import json
import hashlib

logger = logging.getLogger(__name__)


class InterventionType(Enum):
    """Types of proactive interventions"""
    REMINDER = "reminder"
    SUGGESTION = "suggestion"
    ENCOURAGEMENT = "encouragement"
    CHALLENGE = "challenge"
    REVIEW = "review"
    BREAK_REMINDER = "break_reminder"
    RESOURCE_RECOMMENDATION = "resource_recommendation"
    PRACTICE_RECOMMENDATION = "practice_recommendation"
    ACHIEVEMENT = "achievement"
    MILESTONE = "milestone"


@dataclass
class LearningPattern:
    """Learning pattern detected from user behavior"""
    pattern_type: str
    confidence: float
    frequency: float
    last_occurrence: datetime
    related_topics: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ProactiveSuggestion:
    """Suggestion generated by proactive layer"""
    intervention_type: InterventionType
    message: str
    priority: int  # 1-10, higher = more urgent
    confidence: float
    suggested_time: Optional[datetime] = None
    context: Dict[str, Any] = field(default_factory=dict)
    action_required: bool = False
    dismissible: bool = True
    expiry: Optional[datetime] = None


class ProactiveLayer:
    """
    Analyzes learning patterns and generates proactive interventions.
    Predicts user needs and offers timely assistance.
    """
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        
        # User learning patterns by user ID
        self.user_patterns: Dict[str, List[LearningPattern]] = defaultdict(list)
        
        # Intervention history
        self.intervention_history: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
        
        # Learning progress tracking
        self.learning_progress: Dict[str, Dict[str, Any]] = {}
        
        # Pattern detection thresholds
        self.pattern_thresholds = {
            'struggle_pattern': 3,  # Number of struggles to detect pattern
            'mastery_pattern': 5,   # Number of successes to detect mastery
            'time_gap_minutes': 30,  # Time gap for session breaks
            'review_threshold_days': 7  # Days before suggesting review
        }
        
        # Intervention cooldowns (prevent spamming)
        self.intervention_cooldowns: Dict[str, Dict[InterventionType, datetime]] = defaultdict(dict)
        self.default_cooldown_minutes = {
            InterventionType.REMINDER: 60,
            InterventionType.SUGGESTION: 30,
            InterventionType.ENCOURAGEMENT: 15,
            InterventionType.CHALLENGE: 120,
            InterventionType.REVIEW: 1440,  # 24 hours
            InterventionType.BREAK_REMINDER: 45,
            InterventionType.RESOURCE_RECOMMENDATION: 180,
            InterventionType.PRACTICE_RECOMMENDATION: 120,
            InterventionType.ACHIEVEMENT: 10080,  # 1 week
            InterventionType.MILESTONE: 43200  # 30 days
        }
        
        # Initialize pattern detectors
        self.pattern_detectors = self._init_pattern_detectors()
        
        logger.info("Proactive Layer initialized")
    
    def _init_pattern_detectors(self) -> Dict[str, Callable]:
        """Initialize pattern detection functions"""
        return {
            'struggle_cycles': self._detect_struggle_cycles,
            'learning_velocity': self._detect_learning_velocity,
            'session_patterns': self._detect_session_patterns,
            'topic_transitions': self._detect_topic_transitions,
            'forgetting_curve': self._detect_forgetting_curve,
            'engagement_patterns': self._detect_engagement_patterns
        }
    
    async def process(self,
                     user_id: str,
                     recent_interactions: List[Dict[str, Any]],
                     context: Optional[Dict[str, Any]] = None) -> List[ProactiveSuggestion]:
        """
        Process user data to generate proactive suggestions
        
        Args:
            user_id: User identifier
            recent_interactions: List of recent user interactions
            context: Additional context information
            
        Returns:
            List of proactive suggestions
        """
        context = context or {}
        
        try:
            suggestions = []
            
            # Update user patterns
            patterns = await self._update_patterns(user_id, recent_interactions)
            
            # Run all pattern detectors
            for detector_name, detector_func in self.pattern_detectors.items():
                try:
                    detector_suggestions = await detector_func(user_id, recent_interactions, patterns, context)
                    suggestions.extend(detector_suggestions)
                except Exception as e:
                    logger.error(f"Error in pattern detector {detector_name}: {str(e)}")
            
            # Filter and rank suggestions
            suggestions = self._filter_suggestions(user_id, suggestions)
            suggestions = self._rank_suggestions(suggestions)
            
            # Apply cooldowns
            suggestions = self._apply_cooldowns(user_id, suggestions)
            
            # Log generated suggestions
            for suggestion in suggestions:
                self._log_intervention(user_id, suggestion)
                logger.info(f"Generated {suggestion.intervention_type.value} suggestion for user {user_id} (priority: {suggestion.priority})")
            
            return suggestions
            
        except Exception as e:
            logger.error(f"Error in proactive processing: {str(e)}", exc_info=True)
            return []
    
    async def _update_patterns(self, 
                              user_id: str, 
                              interactions: List[Dict[str, Any]]) -> List[LearningPattern]:
        """Update learning patterns for user"""
        patterns = self.user_patterns[user_id]
        
        # Analyze interaction timestamps for temporal patterns
        if len(interactions) > 1:
            timestamps = [i['timestamp'] for i in interactions if 'timestamp' in i]
            if len(timestamps) > 1:
                # Detect session patterns
                session_gaps = [(timestamps[i+1] - timestamps[i]).total_seconds() / 60 
                              for i in range(len(timestamps)-1)]
                
                avg_gap = np.mean(session_gaps) if session_gaps else 0
                if avg_gap < 5:  # Very frequent interactions
                    patterns.append(LearningPattern(
                        pattern_type='intense_session',
                        confidence=0.8,
                        frequency=1.0 / max(avg_gap, 1),
                        last_occurrence=datetime.now(),
                        metadata={'avg_gap_minutes': avg_gap}
                    ))
        
        # Keep only recent patterns (last 30 days)
        cutoff = datetime.now() - timedelta(days=30)
        patterns = [p for p in patterns if p.last_occurrence > cutoff]
        
        self.user_patterns[user_id] = patterns
        return patterns
    
    async def _detect_struggle_cycles(self,
                                     user_id: str,
                                     interactions: List[Dict[str, Any]],
                                     patterns: List[LearningPattern],
                                     context: Dict[str, Any]) -> List[ProactiveSuggestion]:
        """Detect cycles of struggle with specific topics"""
        suggestions: List[ProactiveSuggestion] = []
        
        # Track struggles by topic
        struggle_counts: Dict[str, int] = {}
        recent_struggles = []
        
        for interaction in interactions[-20:]:  # Look at last 20 interactions
            if interaction.get('emotional_state') in ['frustrated', 'confused']:
                topic = interaction.get('topic', 'unknown')
                struggle_counts[topic] = struggle_counts.get(topic, 0) + 1
                recent_struggles.append({
                    'topic': topic,
                    'timestamp': interaction.get('timestamp', datetime.now())
                })
        
        # Check for struggle patterns
        for topic, count in struggle_counts.items():
            if count >= self.pattern_thresholds['struggle_pattern']:
                # Generate intervention
                suggestions.append(ProactiveSuggestion(
                    intervention_type=InterventionType.SUGGESTION,
                    message=f"I notice you've been struggling with {topic}. Would you like to try a different approach or review the fundamentals?",
                    priority=min(5 + count, 9),
                    confidence=0.7 + (count * 0.05),
                    context={'topic': topic, 'struggle_count': count},
                    action_required=False
                ))
        
        return suggestions
    
    async def _detect_learning_velocity(self,
                                       user_id: str,
                                       interactions: List[Dict[str, Any]],
                                       patterns: List[LearningPattern],
                                       context: Dict[str, Any]) -> List[ProactiveSuggestion]:
        """Detect learning velocity changes and provide appropriate interventions"""
        suggestions: List[ProactiveSuggestion] = []
        
        if len(interactions) < 5:
            return suggestions
        
        # Calculate learning velocity (concepts mastered per time)
        mastered_topics = []
        timestamps = []
        
        for interaction in interactions:
            if interaction.get('mastered_concepts'):
                for concept in interaction['mastered_concepts']:
                    mastered_topics.append({
                        'concept': concept,
                        'timestamp': interaction.get('timestamp', datetime.now())
                    })
                timestamps.append(interaction.get('timestamp', datetime.now()))
        
        if len(mastered_topics) < 2:
            return suggestions
        
        # Calculate velocity
        time_span = (max(timestamps) - min(timestamps)).total_seconds() / 3600  # hours
        if time_span > 0:
            velocity = len(mastered_topics) / time_span  # concepts per hour
            
            # Provide feedback based on velocity
            if velocity > 2:  # Fast learner
                suggestions.append(ProactiveSuggestion(
                    intervention_type=InterventionType.ENCOURAGEMENT,
                    message=f"Great progress! You've mastered {len(mastered_topics)} concepts recently. Ready for a challenge?",
                    priority=6,
                    confidence=0.8,
                    context={'velocity': velocity, 'topics_mastered': len(mastered_topics)},
                    action_required=False
                ))
            elif velocity < 0.5 and len(mastered_topics) > 0:  # Slow progress
                suggestions.append(ProactiveSuggestion(
                    intervention_type=InterventionType.SUGGESTION,
                    message="Learning takes time! Would you like to try some different learning materials or take a short break?",
                    priority=7,
                    confidence=0.7,
                    context={'velocity': velocity},
                    action_required=False
                ))
        
        return suggestions
    
    async def _detect_session_patterns(self,
                                      user_id: str,
                                      interactions: List[Dict[str, Any]],
                                      patterns: List[LearningPattern],
                                      context: Dict[str, Any]) -> List[ProactiveSuggestion]:
        """Detect session-based patterns and provide reminders"""
        suggestions: List[ProactiveSuggestion] = []
        
        if len(interactions) < 2:
            return suggestions
        
        # Detect long sessions
        session_start = interactions[0].get('timestamp', datetime.now())
        session_end = interactions[-1].get('timestamp', datetime.now())
        session_duration = (session_end - session_start).total_seconds() / 60  # minutes
        
        if session_duration > 60:  # Over 1 hour
            suggestions.append(ProactiveSuggestion(
                intervention_type=InterventionType.BREAK_REMINDER,
                message=f"You've been learning for {int(session_duration)} minutes. Remember to take short breaks to stay focused!",
                priority=8,
                confidence=0.9,
                context={'duration_minutes': session_duration},
                action_required=False,
                dismissible=True
            ))
        
        # Detect optimal learning times
        if len(interactions) > 10:
            hour_counts: Dict[int, int] = {}
            for interaction in interactions:
                if 'timestamp' in interaction:
                    hour = interaction['timestamp'].hour
                    hour_counts[hour] = hour_counts.get(hour, 0) + 1
            
            if hour_counts:
                optimal_hour = max(hour_counts.items(), key=lambda x: x[1])[0]
                current_hour = datetime.now().hour
                
                if abs(current_hour - optimal_hour) > 3:  # Not optimal time
                    suggestions.append(ProactiveSuggestion(
                        intervention_type=InterventionType.SUGGESTION,
                        message=f"Based on your patterns, you seem most productive around {optimal_hour}:00. Would you like to schedule your next session then?",
                        priority=4,
                        confidence=0.6,
                        context={'optimal_hour': optimal_hour},
                        action_required=True
                    ))
        
        return suggestions
    
    async def _detect_topic_transitions(self,
                                       user_id: str,
                                       interactions: List[Dict[str, Any]],
                                       patterns: List[LearningPattern],
                                       context: Dict[str, Any]) -> List[ProactiveSuggestion]:
        """Detect transitions between topics and suggest connections"""
        suggestions: List[ProactiveSuggestion] = []
        
        if len(interactions) < 3:
            return suggestions
        
        # Track topic sequence
        topics = []
        for interaction in interactions[-10:]:
            topic = interaction.get('topic')
            if topic:
                topics.append(topic)
        
        if len(topics) < 2:
            return suggestions
        
        # Find common transitions
        transitions: Dict[str, int] = {}
        for i in range(len(topics)-1):
            transition = f"{topics[i]} -> {topics[i+1]}"
            transitions[transition] = transitions.get(transition, 0) + 1
        
        if transitions:
            most_common = max(transitions.items(), key=lambda x: x[1])
            if most_common[1] >= 3:  # Frequent transition
                from_topic, to_topic = most_common[0].split(' -> ')
                suggestions.append(ProactiveSuggestion(
                    intervention_type=InterventionType.SUGGESTION,
                    message=f"I notice you often move from {from_topic} to {to_topic}. Would you like to explore how these topics are connected?",
                    priority=5,
                    confidence=0.65,
                    context={'from_topic': from_topic, 'to_topic': to_topic},
                    action_required=False
                ))
        
        return suggestions
    
    async def _detect_forgetting_curve(self,
                                      user_id: str,
                                      interactions: List[Dict[str, Any]],
                                      patterns: List[LearningPattern],
                                      context: Dict[str, Any]) -> List[ProactiveSuggestion]:
        """Detect topics that might need review based on forgetting curve"""
        suggestions = []
        
        # Track when topics were last reviewed
        topic_last_reviewed = {}
        
        for interaction in interactions:
            if interaction.get('mastered_concepts'):
                for concept in interaction['mastered_concepts']:
                    topic_last_reviewed[concept] = interaction.get('timestamp', datetime.now())
        
        current_time = datetime.now()
        
        for topic, last_review in topic_last_reviewed.items():
            days_since_review = (current_time - last_review).days
            
            if days_since_review >= self.pattern_thresholds['review_threshold_days']:
                # Calculate confidence based on forgetting curve
                confidence = max(0, 1.0 - (days_since_review / 30))
                
                suggestions.append(ProactiveSuggestion(
                    intervention_type=InterventionType.REVIEW,
                    message=f"It's been {days_since_review} days since you reviewed {topic}. Would you like to refresh your memory?",
                    priority=min(5 + days_since_review // 2, 8),
                    confidence=confidence,
                    context={'topic': topic, 'days_since_review': days_since_review},
                    action_required=False
                ))
        
        return suggestions
    
    async def _detect_engagement_patterns(self,
                                         user_id: str,
                                         interactions: List[Dict[str, Any]],
                                         patterns: List[LearningPattern],
                                         context: Dict[str, Any]) -> List[ProactiveSuggestion]:
        """Detect engagement patterns and provide motivational interventions"""
        suggestions: List[ProactiveSuggestion] = []
        
        if len(interactions) < 5:
            return suggestions
        
        # Calculate engagement trend
        recent_engagement: List[float] = []
        for interaction in interactions[-10:]:
            if 'engagement_level' in interaction:
                recent_engagement.append(float(interaction['engagement_level']))
        
        if len(recent_engagement) > 3:
            # Check for declining engagement
            half: int = len(recent_engagement) // 2
            first_half = [recent_engagement[i] for i in range(half)]
            second_half = [recent_engagement[i] for i in range(half, len(recent_engagement))]
            
            if first_half and second_half:
                avg_first = np.mean(first_half)
                avg_second = np.mean(second_half)
                
                if avg_second < avg_first * 0.7:  # 30% decline
                    suggestions.append(ProactiveSuggestion(
                        intervention_type=InterventionType.ENCOURAGEMENT,
                        message="I've noticed your engagement has decreased. Would you like to try a different topic or learning style?",
                        priority=7,
                        confidence=0.7,
                        context={'engagement_decline': avg_first - avg_second},
                        action_required=False
                    ))
                elif avg_second > avg_first * 1.3:  # 30% increase
                    suggestions.append(ProactiveSuggestion(
                        intervention_type=InterventionType.ACHIEVEMENT,
                        message=f"Great job staying engaged! Your focus has improved by {int((avg_second/avg_first - 1)*100)}%!",
                        priority=6,
                        confidence=0.8,
                        context={'engagement_increase': avg_second - avg_first},
                        action_required=False
                    ))
        
        return suggestions
    
    def _filter_suggestions(self, 
                           user_id: str, 
                           suggestions: List[ProactiveSuggestion]) -> List[ProactiveSuggestion]:
        """Filter suggestions based on relevance and history"""
        filtered = []
        
        # Get recent interventions
        recent = self.intervention_history[user_id][-20:] if user_id in self.intervention_history else []
        recent_types = [i['type'] for i in recent]
        recent_messages = [i['message'] for i in recent]
        
        for suggestion in suggestions:
            # Filter out duplicate types in quick succession
            if suggestion.intervention_type.value in recent_types[-3:]:
                continue
            
            # Filter out similar messages
            if any(self._message_similarity(suggestion.message, msg) > 0.8 for msg in recent_messages[-5:]):
                continue
            
            # Filter out low confidence suggestions
            if suggestion.confidence < 0.5:
                continue
            
            filtered.append(suggestion)
        
        return filtered
    
    def _message_similarity(self, msg1: str, msg2: str) -> float:
        """Calculate similarity between two messages"""
        # Simple Jaccard similarity for now
        words1 = set(msg1.lower().split())
        words2 = set(msg2.lower().split())
        
        intersection = words1 & words2
        union = words1 | words2
        
        return len(intersection) / len(union) if union else 0
    
    def _rank_suggestions(self, suggestions: List[ProactiveSuggestion]) -> List[ProactiveSuggestion]:
        """Rank suggestions by priority and confidence"""
        # Calculate composite score
        for suggestion in suggestions:
            suggestion.priority = int(suggestion.priority * suggestion.confidence)
        
        # Sort by priority descending
        suggestions.sort(key=lambda x: x.priority, reverse=True)
        
        return suggestions
    
    def _apply_cooldowns(self, 
                        user_id: str, 
                        suggestions: List[ProactiveSuggestion]) -> List[ProactiveSuggestion]:
        """Apply cooldowns to prevent suggestion spam"""
        valid_suggestions = []
        current_time = datetime.now()
        
        for suggestion in suggestions:
            intervention_type = suggestion.intervention_type
            
            # Check cooldown
            last_intervention = self.intervention_cooldowns[user_id].get(intervention_type)
            
            if last_intervention:
                cooldown_minutes = self.default_cooldown_minutes.get(intervention_type, 60)
                time_since_last = (current_time - last_intervention).total_seconds() / 60
                
                if time_since_last < cooldown_minutes:
                    continue
            
            valid_suggestions.append(suggestion)
        
        return valid_suggestions
    
    def _log_intervention(self, user_id: str, suggestion: ProactiveSuggestion):
        """Log intervention for history and cooldown tracking"""
        intervention = {
            'type': suggestion.intervention_type.value,
            'message': suggestion.message,
            'priority': suggestion.priority,
            'confidence': suggestion.confidence,
            'timestamp': datetime.now(),
            'context': suggestion.context
        }
        
        self.intervention_history[user_id].append(intervention)
        
        # Update cooldown
        self.intervention_cooldowns[user_id][suggestion.intervention_type] = datetime.now()
        
        # Keep only last 100 interventions
        if len(self.intervention_history[user_id]) > 100:
            self.intervention_history[user_id] = self.intervention_history[user_id][-100:]
    
    def record_interaction(self, 
                          user_id: str, 
                          interaction_type: str,
                          topic: Optional[str] = None,
                          emotional_state: Optional[str] = None,
                          mastered_concepts: Optional[List[str]] = None,
                          engagement_level: Optional[float] = None):
        """Record a user interaction for pattern analysis"""
        interaction = {
            'type': interaction_type,
            'timestamp': datetime.now(),
            'topic': topic,
            'emotional_state': emotional_state,
            'mastered_concepts': mastered_concepts or [],
            'engagement_level': engagement_level
        }
        
        # Update learning progress
        if user_id not in self.learning_progress:
            self.learning_progress[user_id] = {
                'topics_studied': set(),
                'concepts_mastered': set(),
                'struggle_topics': defaultdict(int),
                'session_count': 0,
                'total_interactions': 0,
                'last_active': datetime.now()
            }
        
        progress = self.learning_progress[user_id]
        progress['total_interactions'] += 1
        progress['last_active'] = datetime.now()
        
        if topic:
            progress['topics_studied'].add(topic)
        
        if mastered_concepts:
            progress['concepts_mastered'].update(mastered_concepts)
        
        if emotional_state in ['frustrated', 'confused'] and topic:
            progress['struggle_topics'][topic] += 1
        
        # Store in user's interaction history (would go to database in production)
        # For now, we'll just log it
        logger.debug(f"Recorded interaction for user {user_id}: {interaction_type}")
    
    def get_user_insights(self, user_id: str) -> Dict[str, Any]:
        """Get insights about a user's learning patterns"""
        if user_id not in self.learning_progress:
            return {}
        
        progress = self.learning_progress[user_id]
        patterns = self.user_patterns.get(user_id, [])
        
        return {
            'topics_studied': list(progress['topics_studied']),
            'concepts_mastered': len(progress['concepts_mastered']),
            'struggle_areas': dict(progress['struggle_topics']),
            'total_interactions': progress['total_interactions'],
            'last_active': progress['last_active'],
            'detected_patterns': [
                {
                    'type': p.pattern_type,
                    'confidence': p.confidence,
                    'last_occurrence': p.last_occurrence
                }
                for p in patterns
            ],
            'recent_interventions': self.intervention_history.get(user_id, [])[-5:]
        }
    
    def get_suggestion_statistics(self, user_id: str) -> Dict[str, Any]:
        """Get statistics about suggestions for a user"""
        interventions = self.intervention_history.get(user_id, [])
        
        if not interventions:
            return {}
        
        # Count by type
        type_counts: Dict[str, int] = {}
        for intervention in interventions:
            type_counts[intervention['type']] = type_counts.get(intervention['type'], 0) + 1
        
        # Calculate acceptance rate (simplified)
        total = len(interventions)
        
        return {
            'total_suggestions': total,
            'suggestion_breakdown': dict(type_counts),
            'average_priority': np.mean([i['priority'] for i in interventions]),
            'average_confidence': np.mean([i['confidence'] for i in interventions]),
            'last_suggestion': interventions[-1] if interventions else None
        }