import os
from pathlib import Path

backend_dir = Path("/Users/princegupta/Downloads/JARVIS-master/jarvis-system/backend")

items = [
    "core/__init__.py",
    "core/engine.py",
    "core/pipeline/__init__.py",
    "core/pipeline/reactive_layer.py",
    "core/pipeline/cognitive_layer.py",
    "core/pipeline/metacognitive_layer.py",
    "core/pipeline/proactive_layer.py",
    "core/pipeline/creative_layer.py",
    "core/config/__init__.py",
    "core/config/settings.yaml",
    "core/config/personality.yaml",
    "core/config/university_profiles/mu.yaml",
    "core/config/university_profiles/iit_delhi.yaml",
    "core/config/university_profiles/vtu.yaml",

    "knowledge/__init__.py",
    "knowledge/rag_engine/__init__.py",
    "knowledge/rag_engine/syllabus_aware_rag.py",
    "knowledge/rag_engine/document_processor.py",
    "knowledge/rag_engine/chunking_strategies.py",
    "knowledge/rag_engine/embedding_manager.py",
    "knowledge/rag_engine/query_enhancer.py",
    "knowledge/syllabus/__init__.py",
    "knowledge/syllabus/syllabus_parser.py",
    "knowledge/syllabus/topic_extractor.py",
    "knowledge/syllabus/exam_patterns.py",
    "knowledge/syllabus/question_bank.py",
    "knowledge/syllabus/difficulty_mapper.py",
    "knowledge/curriculum_mapper/__init__.py",
    "knowledge/curriculum_mapper/subject_hierarchy.py",
    "knowledge/curriculum_mapper/prerequisite_graph.py",
    "knowledge/curriculum_mapper/learning_paths.py",

    "emotional_intelligence/__init__.py",
    "emotional_intelligence/emotion_detector/__init__.py",
    "emotional_intelligence/emotion_detector/voice_analyzer.py",
    "emotional_intelligence/emotion_detector/text_sentiment.py",
    "emotional_intelligence/emotion_detector/multimodal_fusion.py",
    "emotional_intelligence/emotion_detector/emotion_state.py",
    "emotional_intelligence/response_adapters/__init__.py",
    "emotional_intelligence/response_adapters/mentorship_mode.py",
    "emotional_intelligence/response_adapters/confidence_booster.py",
    "emotional_intelligence/response_adapters/stress_reduction.py",
    "emotional_intelligence/response_adapters/engagement_mode.py",
    "emotional_intelligence/emotional_memory/__init__.py",
    "emotional_intelligence/emotional_memory/emotional_history.py",
    "emotional_intelligence/emotional_memory/trigger_identifier.py",
    "emotional_intelligence/emotional_memory/intervention_log.py",

    "proactive_assistant/__init__.py",
    "proactive_assistant/pattern_analyzer/__init__.py",
    "proactive_assistant/pattern_analyzer/learning_patterns.py",
    "proactive_assistant/pattern_analyzer/difficulty_tracker.py",
    "proactive_assistant/pattern_analyzer/time_analyzer.py",
    "proactive_assistant/pattern_analyzer/performance_predictor.py",
    "proactive_assistant/scheduler/__init__.py",
    "proactive_assistant/scheduler/revision_planner.py",
    "proactive_assistant/scheduler/exam_preparation.py",
    "proactive_assistant/scheduler/break_recommender.py",
    "proactive_assistant/scheduler/reminder_system.py",
    "proactive_assistant/intervention_engine/__init__.py",
    "proactive_assistant/intervention_engine/suggestion_generator.py",
    "proactive_assistant/intervention_engine/timing_optimizer.py",
    "proactive_assistant/intervention_engine/feedback_collector.py",

    "academic_qa/__init__.py",
    "academic_qa/response_formatter/__init__.py",
    "academic_qa/response_formatter/marks_allocator.py",
    "academic_qa/response_formatter/diagram_generator.py",
    "academic_qa/response_formatter/derivation_builder.py",
    "academic_qa/response_formatter/numerical_solver.py",
    "academic_qa/response_formatter/code_formatter.py",
    "academic_qa/exam_simulator/__init__.py",
    "academic_qa/exam_simulator/question_generator.py",
    "academic_qa/exam_simulator/answer_evaluator.py",
    "academic_qa/exam_simulator/time_manager.py",
    "academic_qa/concept_explainer/__init__.py",
    "academic_qa/concept_explainer/step_by_step.py",
    "academic_qa/concept_explainer/analogy_generator.py",
    "academic_qa/concept_explainer/visualization.py",
    "academic_qa/concept_explainer/prerequisite_check.py",

    "memory_system/__init__.py",
    "memory_system/long_term/__init__.py",
    "memory_system/long_term/vector_store.py",
    "memory_system/long_term/knowledge_graph.py",
    "memory_system/long_term/sqlite_store.py",
    "memory_system/short_term/__init__.py",
    "memory_system/short_term/conversation_buffer.py",
    "memory_system/short_term/context_window.py",
    "memory_system/short_term/working_memory.py",
    "memory_system/episodic/__init__.py",
    "memory_system/episodic/session_logger.py",
    "memory_system/episodic/learning_milestones.py",
    "memory_system/episodic/interaction_history.py",

    "data/raw/textbooks/README.md",
    "data/raw/syllabus/README.md",
    "data/raw/question_papers/README.md",
    "data/processed/chunks/README.md",
    "data/processed/embeddings/README.md",
    "data/processed/indices/README.md",
    "data/user_data/profiles/README.md",
    "data/user_data/learning_history/README.md",
    "data/user_data/emotional_data/README.md",

    "api/__init__.py",
    "api/rest/__init__.py",
    "api/rest/routes.py",
    "api/rest/controllers/__init__.py",
    "api/rest/controllers/query_controller.py",
    "api/rest/controllers/study_controller.py",
    "api/rest/controllers/profile_controller.py",
    "api/rest/middleware/__init__.py",
    "api/rest/middleware/auth.py",
    "api/rest/middleware/logging.py",
    "api/websocket/__init__.py",
    "api/websocket/handlers.py",
    "api/websocket/events.py",

    "services/__init__.py",
    "services/llm/__init__.py",
    "services/llm/local_llm.py",
    "services/llm/prompt_templates.py",
    "services/llm/response_parser.py",
    "services/voice/__init__.py",
    "services/voice/speech_to_text.py",
    "services/voice/text_to_speech.py",
    "services/voice/voice_activity.py",
    "services/vision/__init__.py",
    "services/vision/diagram_reader.py",
    "services/vision/formula_ocr.py",
    "services/vision/hand_drawing.py",

    "tools/__init__.py",
    "tools/code_executor/__init__.py",
    "tools/code_executor/safe_executor.py",
    "tools/code_executor/code_analyzer.py",
    "tools/code_executor/debug_assistant.py",
    "tools/calculator/__init__.py",
    "tools/calculator/scientific_calc.py",
    "tools/calculator/unit_converter.py",
    "tools/calculator/formula_evaluator.py",
    "tools/visualizer/__init__.py",
    "tools/visualizer/graph_plotter.py",
    "tools/visualizer/circuit_drawer.py",
    "tools/visualizer/data_visualizer.py",

    "utils/__init__.py",
    "utils/logger.py",
    "utils/config_loader.py",
    "utils/helpers.py",
    "utils/validators.py",
    "utils/decorators.py",

    "tests/__init__.py",
    "tests/unit/__init__.py",
    "tests/unit/test_syllabus_aware_rag.py",
    "tests/unit/test_emotion_detector.py",
    "tests/unit/test_proactive_assistant.py",
    "tests/unit/test_response_formatter.py",
    "tests/integration/__init__.py",
    "tests/integration/test_academic_pipeline.py",
    "tests/integration/test_emotional_response.py",
    "tests/fixtures/sample_syllabus.pdf",
    "tests/fixtures/sample_textbook.pdf",

    "scripts/setup_university.py",
    "scripts/import_textbooks.py",
    "scripts/generate_embeddings.py",
    "scripts/migrate_database.py",

    "requirements/base.txt",
    "requirements/rag.txt",
    "requirements/emotion.txt",
    "requirements/voice.txt",
    "requirements/dev.txt",

    "main.py",
    ".env.example",
    "README.md",
    "docker-compose.yml"
]

backend_dir.mkdir(parents=True, exist_ok=True)

for item in items:
    path = backend_dir / item
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        if path.suffix in [".pdf"]:
            path.touch()
        else:
            path.touch()

print("Scaffold complete.")
